version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: image_voting_db
    ports:
      - "5432:5432"

  server:
    build: server
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: image_voting_db
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - app_network

  client:
    build: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      REACT_APP_API_URL: "http://server:8000"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
